name: VanillaCommands
version: 1.0.0-alpha1
api: 3.0.0
main: DenielWorld\VanillaCommands\Loader
author: DenielWorld
description: "PMMP Plugin that adds vanilla commands on your server | Will be customizable in the future"
permissions:
  vanillacommands:
    default: false
    description: "Use everything in VanillaCommands"
    children:
      vanillacommands.state:
        default: false
        description: "Takes away all abilities from a player"
        children:
          vanillacommands.state.mute:
            default: false
            description: "Takes away speaking rights from a player"
          vanillacommands.state.worldbuilder:
            default: false
            description: "Takes away building rights from a player"
          vanillacommands.state.mayfly:
            default: false
            description: "Takes away flying rights from a player"
      vanillacommands.command:
            default: op
            description: "Lets the player use everything in VanillaCommands"
            children:
              vanillacommands.command.ability:
                default: op
                description: "Lets you manage abilities of a certain player"
              vanillacommands.command.alwaysday:
                default: op
                description: "Lets you make the time always be day"
              vanillacommands.command.clear:
                default: op
                description: "Lets you manage other player's inventories/remove items from their inventories"
              vanillacommands.command.connect:
                default: true
                description: "Transfer to a different server"
              vanillacommands.command.immutableworld:
                default: op
                description: "Set immutable worlds for the current game session"
              vanillacommands.command.mobevent:
                default: op
                description: "Control specific mob events for the current game sessions"#Pretty useless with the current mob system in PMMP
              vanillacommands.command.playsound:
                default: op
                description: "Play a sound at a specific coordinate/to a specific player"
              vanillacommands.command.setblock:
                default: op
                description: "Set a specific block at a specific location"
              vanillacommands.command.setmaxplayers:
                default: op
                description: "Set the max amount of players for the current game session"
              vanillacommands.command.tag:
                default: op
                description: "Manage a player's tag"
